export const navigationPadding = '20px'
export const contentWidth = '740px'
export const contentWidthPadding = '20px'
export const wideContentWidth = '980px'
export const mobileWidth = '580px'
export const mobileGnbWidth = '1024px'
